"""Versículos vacíos cuyo texto está pegado al anterior.

El número impreso quedó dentro del versículo previo y el hueco se suplía
con otra Biblia. El texto es el de Torres Amat; solo se parte.
"""

FUSIONES = (
    (
        'Genesis 26:17',
        'Genesis 26:18',
        'Partió pues Isaac, para ir hácia el torrente de Gerara, y habitar alli:.',
        ' 18 ',
        'É hizo abrir de muevo los otros pozos, que habian cavado los siervos de su padre Abraham, y que, muerto éste, habian cegado en otro tiempo los Philisteos: y les dió los mismos nombres que su padre les habia dado antes.',
    ),
    (
        'Genesis 31:20',
        'Genesis 31:21',
        'No quiso Jacob manifestarle á sil suegro su partida.',
        ' 21 ',
        'Y como se hubiese ya marchado con todo lo que le = pertenecia, y vadeado el rio Euphrates, se encaminase hácia el monte de Galaad',
    ),
    (
        'Genesis 39:18',
        'Genesis 39:19',
        'Mas como me oyó gritar soltó la capa que yo tenia asida, y huyóse afuera.',
        ' 19 ',
        'El amo oidas tales cosas, y demasiadamente crédulo á las palabras de su mujer, enojóse sobremanera',
    ),
    (
        'Exodus 8:4',
        'Exodus 8:5',
        'Y serás atormentado de las ranas tú, tu pueblo, y todos bus servidores.',
        ' 5 ',
        'Dijo, pues, el Señor á Moysés: Dile á Aaron: Extiende tu mano sobre los rios y sobre los arroyos, y las lagunas, y haz salir ranas sobre la tierra de Eeypto.',
    ),
    (
        'Exodus 8:24',
        'Exodus 8:25',
        'Y así lo hizo el Señor. Enjambres de moscas molestísimas y dañinas vinieron á las casas de Pharaon y de sus criados, y á toda la tierra de Egypto, y quedó el país inficionado de tales moscas.',
        ' 25 ',
        'Llamó entonces Pharaon á Moysés y Aaron, y dijoles: Id, y sacrificad á vuestro Dios, sin salir de esta tierra.',
    ),
    (
        'Exodus 37:26',
        'Exodus 37:27',
        'Y le cubrió de oro purísimo, como igualmente á su rejilla, y los costados, y las puntas.',
        ' 27 ',
        'Y le ciñó de una eornisa de oro, poniendo debajo de la cornisa, en cada lado, dos anillos de oro para meter por ellos las varas con que se pudiese trasportar.',
    ),
    (
        'Leviticus 9:18',
        'Leviticus 9:19',
        'Degolló asimismo el buey y el carnero como hostias jel e o. a o o Mo Ao de pacíficas del pueblo, y le presentaron sus hijos la sangre, la cual derramó sobre el altar al rededor.',
        ' 19 ',
        'Mas el sebo del buey, y la cola del carnero, y los ria) ñones con su grosura, y la telilla del hígado "Lo pusieron sobre los pechos de las victimas; y quemados sobre el altar los sebos',
    ),
    (
        'Leviticus 18:12',
        'Leviticus 18:13',
        'No tendrás que ver con la hermana de tu padre; porque es carne de tu mismo padre.',
        ' 13 ',
        'No tendrás que ver con la hermana de tu madre; porque es carne de tu madre.',
    ),
    (
        'Deuteronomy 7:4',
        'Deuteronomy 7:5',
        'Porque seducirán á tus hijos para que me abandonen, y adoren á dioses extranjeros: con lo que se irritará el furor del Señor, y bien presto acabará contigo.',
        ' 5 ',
        'Por el contrario, esto es lo que debeis hacer con ellos: derribad sus altares y haced pedazos las estátuas, talad sus bosques profanos, y quemad los ídolos',
    ),
    (
        'Deuteronomy 9:21',
        'Deuteronomy 9:22',
        'Y arrebatando vuestro pecado, es á saber, el becerro que habiais hecho, le eché al fuego, y desmenuzándole, y reducióndole todo á polvo, le arrojé al arroyo que desciende del monte.',
        ' 22 ',
        'Tambien en el lugar que por eso se llamó del Incendio, en el otro de la Tentación y en el llamado Sepuleros de la Concupiscencia ó ambtojo, provocasteis al Señor Y',
    ),
    (
        'Joshua 21:25',
        'Joshua 21:26',
        'Y de la media tribu de Manassés á Thanach, y Gethremmon con sus contornos: dos ciudades.',
        ' 26 ',
        'En todo se dieron diez ciudades y sus alrededores á los Levitas hijos de Caath que eran de inferior grado al sacerdotal',
    ),
    (
        'Judges 1:32',
        'Judges 1:33',
        'Antes bien moró en medio de los Chananéos que habitaban aquella tierra, y no los exterminó.',
        ' 33 ',
        'Del mismo modo Nephthalí no quiso acabar con los habitantes de Bethsames y de Beth anath, sino que vivió entre los Chananéos naturales de la tierra, haciendo tributarios á los Bethsamitas y Bethanitas. iú',
    ),
    (
        'Judges 7:11',
        'Judges 7:12',
        'Y cuando oyeres lo que hablan los Madianitas, quedarás mas animoso, y asaltarás despues con mas confianza su campamento. Partió pues Gedeon, con su criado Phara, hácia aquel paraje del campamento donde estaban las centinelas del ejército enemigo.',
        ' 12 ',
        'Es de advertir que los Madianitas y Amalecitas, y todos los pueblos orientales yacian tendidos en el valle, como una muchedumbre de langostas; y sus camellos eran sin número, como las arenas de la orilla del mar.',
    ),
    (
        'Judges 17:11',
        'Judges 17:12',
        'Condescendió y quedóse en casa de Michas, quien le trató como á uno de sus hijos.',
        ' 12 ',
        'Y Michas le consagró las manos; y tuvo en su casa á este jóven en calidad de sacerdote',
    ),
    (
        'I Samuel 19:20',
        'I Samuel 19:21',
        'Envió &amp;amp;##x27; pues Saul =&amp;gt; soldados: para prender á David: s los cuales habiendo visto un coro de Profetas que profetizaban ó cantaban alabanzas d Dios, y á Samuel que presidia entre. ellos, fueron tambien arrebatados del espíritu del Señor, y comenzaron á alabar á Dios, como los otros?',
        ' 21 ',
        'Habiéndose a referido. esto á Saul,: envió a otros &amp;gt;soldados; los cuales asimismo se púsiéron á alabar á Dios, Despachó otros por tercera vez, que igualmente se pusieron á cantar las alabanzas de Dios. Entonces Saul, lleno de cólera',
    ),
    (
        'I Samuel 20:13',
        'I Samuel 20:14',
        'No hagais, oh Señor, bien áJonathás, sino mucho mal. Pero si continuare la mala voluntad de mi padre contra tí, te lo avisaré tambien, y te daré licencia á fin de que te vayas en paz; y el Señor sea contigo, como estuvo con mi padre.',
        ' 14 ',
        'Y tú, si yo viviere, me tratarás con toda la bondad posible; mas si yo murlere',
    ),
    (
        'II Samuel 15:1',
        'II Samuel 15:2',
        'Despues de esto Absalom se equipó de carrozas, tomó gentes de á caballo, y cincuenta guardias que fuesen corriendo delante de él.',
        ' 2 ',
        'YE levantándose de madrugada, se ponia á la entrada de la puerta; pedir y á á todos los que tenian negocios que tratar, y venlan á justicia al rey, llamábalos Absalom, y decíales; ¿De dónde eres tú? Respondíale el hombre: Yo, siervo tuyo, soy de tal tribu de Israél.',
    ),
    (
        'II Chronicles 35:23',
        'II Chronicles 35:24',
        'All fué herido por los flecheros, y dijo á sus ertados: sacadme fuera del combate, pues estoy gravemente herido.',
        ' 24 ',
        'Jillos le pasaron de su coche á otro, que le seguia segun estilo de los reyes, y le llevaron á Jerusalem, donde murió; y fué sepultado en el panteon de sus padres. Lloráronle todo Judá y Jerusalen',
    ),
    (
        'Job 38:13',
        'Job 38:14',
        '¿Has cogido con tus manos los polos de la tierra, y sacudidola, á fin de limpiar y expeler de ella á los impíos?',
        ' 14 ',
        'Volverá á ser lodo d polvo el sello, y durará como un vestido que está consumiéndose.',
    ),
    (
        'Psalms 55:11',
        'Psalms 55:12',
        'A Dios celebraré por las promesas que me tiene hechas, alabaré al Señor por ellas. En Dios teneo mi esperanza, nada temeré de cuanto pueda hacer contra mí el hombre.',
        ' 12 ',
        'A mi cuidado quedan, oh Dios, los votos que te he hecho, que cuompliré cantando tus alabanzas',
    ),
    (
        'Psalms 64:11',
        'Psalms 64:12',
        'Hincha sus canales: multiplica sus producciones: con los suaves rocíos se regocijarán las plantas todas.',
        ' 12 ',
        'Coronarás el año de tu bondad, y serán fertilísimos tus campos.',
    ),
    (
        'Proverbs 16:1',
        'Proverbs 16:2',
        'Del hombre es preparar dentro de su alma el razonamiento; y del Señor el gobernar la lengua.',
        ' 2 ',
        'Todas las acciones del hombre están patentes á la humana vista; mos el Señor pesa los espíritus Ó JUz 200 L08 Inleriores, d. Dirige hácia el Señor tus obras; y tendrán buen éxito tus designios.',
    ),
    (
        'Proverbs 19:26',
        'Proverbs 19:27',
        'Infame es y desventurado aquel que da pesadumbres á Su padre, y echa de sí d de caso á la madre.',
        ' 27 ',
        'No te canses, hijo mio, de escuchar las advertencias, ni quieras lenorar las máximas juiciosas.',
    ),
    (
        'Ecclesiastes 7:18',
        'Ecclesiastes 7:19',
        'Nomultipliques pecados sobre pecados, ni quieras ser insensato difiriendo la enmienda; no sea que te coja la muerte antes de tiempo.',
        ' 19 ',
        'Bueno es que socorras al justo; mas no por eso retires tu mano de otros que no lo son: pues quien teme á Dios, á nacie desecha',
    ),
    (
        'Isaiah 29:11',
        'Isaiah 29:12',
        'Y las visiones d profecías de todos estos serán para vosotros como palabras de un libro sellado, que cuando le dieren á uno que sabe leer, y le digan: Léele; responderá: No puedo, porque está sellado.',
        ' 12 ',
        'Y si le dieren á uno que no sabe leer, y le dicen: Léele; responderá: No sé leer',
    ),
    (
        'Isaiah 39:2',
        'Isaiah 39:3',
        'Y se alegró mucho de esto Ezechias, e hízoles ver el repuesto d recámara de los aromas, y de la plata, y del oro, y de los bálsamos, y de los ungiientos preciosos, y todas las estancias de sus muebles, y todo cuanto se hallaba en sus tesoros. No dejó Ezechias cosa alguna de su casa ó en su poder, que no se la mostrara.',
        ' 3 ',
        'Mas entró despues el Profeta Isalas á ver al rey Ezechias, y le preeuntó:¿Qué han dicho esos hombres, y de dónde vienen? Han venido á mí, respondió Ezechias, de lejas tierras; Y de Babylonia. ig',
    ),
    (
        'Jeremiah 25:11',
        'Jeremiah 25:12',
        'Y toda esta tierra quedará hecha una soledad espantosa; y todas estas gentes servirán al rey de Babylonia por espacio de setenta años.',
        ' 12 ',
        'Y cumplidos que sean los setenta años, yo tomaré residencia al rey de Babylonia y á aquella nacion, dice el 389 JEREMIAS. Señor, castigando sus iniquidades, y á todo el país delos Chaldéos, reduciéndolo á un eterno páramo.',
    ),
    (
        'Ezekiel 36:33',
        'Ezekiel 36:34',
        'Hsto dice el Señor Dios: En el dia en que yo os purificaré de todas vuestras maldades, y poblaré vuestras ciudades, y repararé lo arruinado.',
        ' 34 ',
        'Y se verá cultivada la tierra yerma, donde antes no veia el viajero mas que desolacion. Dirán: Aquella tierra inculta está hecha ahora un jardin de delicias, y las ciudades desiertas, abandonadas y derruidas, se hallan ya restauradas y fortificadas.',
    ),
    (
        'Ezekiel 47:8',
        'Ezekiel 47:9',
        'Y díjome el Angel: Estas aguas que corren hácia los montones de arena al Oriente, y descienden á la llanura del Desierto, entrarán en el mar y saldrán; y las aguas del mar quedarán salutíferas.',
        ' 9 ',
        'Y todo animal viviente delos que andan serpeando por 20 donde pasa el arroyo tendrá vida; y habrá allí gran cantidad de peces despues que llegaren estas aguas: y todos aquellos á quienes bocare este arroyo tendrán salud y vida.',
    ),
    (
        'Luke 17:11',
        'Luke 17:12',
        'Caminando Jesus hácia Jerusalem, atravesaba las provincias de Samaria y de Galiléa.',
        ' 12 ',
        'Y estando para entrar en una poblacion, le salieron al encuentro diez leprosos, los cuales se pararon á lo lejos',
    ),
    (
        'Luke 17:35',
        'Luke 17:36',
        'Estarán dos mujeres moliendo juntas; la una será libertada, y la otra abandonada: dos hombres en el mismo campo; el uno será libertado, y el otro abandonado.',
        ' 36 ',
        '¡¿ Dónde, Señor, replicaron ellos, dónde será esto?',
    ),
    (
        'Acts 21:11',
        'Acts 21:12',
        'El cual viniendo á visitarnos, cogió el ceñidor de Pablo: y atándose con él los piés, y las manos, dijo: Esto dice el Espíritu Santo: Así atarán los Judíos en Jerusalem al hombre, cuyo es este E y entregarle han en manos de los Gentiles.',
        ' 12 ',
        'Lo que oido, rogábamos á Pablo, así nosotros, como los de aquel pueblo, que no pasase á Jerusalem.',
    ),
    (
        'Acts 28:11',
        'Acts 28:12',
        'Al cabo de tres meses, nos hicimos á la vela en una nave Alejandrina, que habia invernado en aquella isla, y tenia e la divisa de Castor y Polux.',
        ' 12 ',
        'Y habiendo llegado á Syracusa, nos detuvimos allí tres dias.',
    ),
)
